# Site settings
title: Dota 2 Replay Manager
email: github@computerfr33k.me
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.computerfr33k.me/Dota2_Replay_Manager" # the base hostname & protocol for your site
github_username:  computerfr33k

# Build settings
markdown: kramdown
